# version: '2'

services:
  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress
    container_name: wp
    ports:
     - "8080:80" # ポート番号の設定
     # Local machine port.. : Container port..たぶん
    restart: always
    depends_on:
     - mysql
    links:
     - mysql
    volumes: # may be specifid only path here. more specify around line:39.
     - ./wp-content/themes:/home/ka2yuki/projects_on_wsl/fjgsk
      # Container : Local-machine

      # todo: 
      # - volumeに Name指定する

      # Issues:
      #  反映される：docker-compose.ymlの階層に展開されてしまう。。2024年12月25日
      #  A. docker-compose.yml is included in Folder that your projects. may be..

      # Draft:
      #  - wordpress:/var/www/html # container:local
      #  - ./www/html:/var/www/html/
      #  - ./wp-content:/var/www/html/wp-content
    env_file: .env # wordpress password の定義に .env file

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306" #ポート番号の設定
    restart: always
    volumes:
     - db:/var/lib/mysql
    #  - "./.data/db:/var/lib/mysql"
    env_file: .env # wordpress password の定義に .env file

volumes:
  wordpress:
  db:
